### ISSUE TITLE
Criar o select para baixar os registros Sas no FI-admin para criar o índice

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin-migration#5]

**Comment by anakatiacamilo** [comment]
Feito com a ajuda do fabio.brito


SELECT a.id,
       b.reference_ptr_id,
       a.reference_title,
       LEFT(a.publication_date_normalized,4),
       b.title,
       b.english_translated_title,
       b.individual_author,
       b.corporate_author,
       b.pages,
       b.source_id,
       c.title_serial,
       c.volume_serial,
       c.issue_number
FROM biblioref_reference AS a,
     biblioref_referenceanalytic AS b,
     biblioref_referencesource AS c
WHERE
LEFT(a.literature_type,1) = 'S'
AND
 b.title <> ''
AND
  a.id = b.source_id
AND
  b.source_id = c.reference_ptr_id;
