### ISSUE TITLE
Cierre de LILDBI-Web de LIPECS para contribución

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin-migration#56]
Confirmar si el LILDBI-Web no recibe más contribución y si todos los usuarios fueron creados en BIREME Accounts

Por lo menos un més para que todos tengan finalizado y certificado sus registros

**Comment by suelisuga** [comment]
Fernando Ardito - UPCH <fernando.ardito.s@upch.pe>
Sex, 14/08/2020 18:18
Para: Suga, Sueli Mitiko Yano (BIR)
Hola Sueli:

Espero que toda la familia esté muy bien esta época de pandemia.

Un favor, los registros LIPECS de REPEBIS actualmente están mostrados en: http://repebis.upch.edu.pe/ , en la última reunión dijiste que ya se habían migrado los registros de Perú por lo que para que no se tengan dos portales con los mismos registros, ¿ tu crees que ya podríamos desactivar el portal de REPEBIS almacenado en el servidor de la Universidad Peruana Cayetano Heredia?

Para realizar este cambio necesito que me envies el link actual en BIREME, de los registros de LIPECS para colocarlo en el portal de la BVS Perú.

Espero tus comentarios.

Gracias, un abrazo.

Fernando

Ing. Fernando Ardito
Jefe del Área de Publicaciones Científicas
Coordinador Nacional de REPEBIS/BIREME/OPS
Universidad Peruana Cayetano Heredia
Lima - Perú

**Comment by anakatiacamilo** [comment]
@suelisuga, eu apaguei o seu comentário, porque, tinha menções de e-mail.
Resumindo 
O Fernando quer o link do iaHx da LIPECS dos registros migrados e quer saber se pode desativar o REPEBIS http://repebis.upch.edu.pe/ já tem os mesmos registros que foram migrados.

O chamado 7500 do ocomon trata do processamento e publicação dos dados do Perú esta em atendimento.
