### ISSUE TITLE
Carga de datos de LIPECS en FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin-migration#57]

**Comment by suelisuga** [comment]
Camilo, Ana Katia (BIR)
Sáb, 08/08/2020 00:04
Para: Suga, Sueli Mitiko Yano (BIR)
Cc: #BIR:Lilacs
Susu,

Segue a lista de Registros SciELO que migraram no mês  passado, eu estava esperando terminar o Relatório dos  registros LIPECS para mandar os dois juntos, como estamos trabalhando ainda nos relatórios do LIPECS. Envio somente do SciELO agora.
Katinha

Analista de Sistemas

**Comment by suelisuga** [comment]
Total Original | 20495
-- | --
Total Migrado | 8700
Total Marcado | 11732
Total Não Migrado | 63

Origen:
![image](https://user-images.githubusercontent.com/13105683/94020654-8ca21200-fd89-11ea-97ac-3c3ebaff4469.png)

Migrado en FI-Admin en el día de hoy 23/09/2020:
![image](https://user-images.githubusercontent.com/13105683/94020844-c07d3780-fd89-11ea-972e-b54d6843d932.png)
Registros de fascículos deben ser sacados del número final de registros porque no son presentados en la interfaz de búsqueda:
![image](https://user-images.githubusercontent.com/13105683/94021202-236ece80-fd8a-11ea-90de-d3914e6d044b.png)

**Comment by anakatiacamilo** [comment]
Os Registros LIPECS foram marcados no FI-ADMIN

![fiadmin_lipecs](https://user-images.githubusercontent.com/19270675/98030902-75c2f680-1df0-11eb-921c-8b9cf13298ea.jpg)
