### ISSUE TITLE
Desenvolver processo para filtrar base específica a partir do FI-Admin

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin-migration#8]

**Comment by marcoslmori** [comment]
dependente do #1 `para avançar

**Comment by falbrito** [comment]
Desenvolvido processo que faz filtragem por base de dados.
Esta sendo utilizado para a busca os campos 904 (indexado em) e 4 (base de dados).

Lógica utilizada:
mx iso=${DB_ORIGINAL}/fiadmin.iso "proc=if v904:'${FI}' or v4:'${FI}' then else 'd*' fi" append=$HUMAN_FI -all now
